# Generated by Django 5.1.4 on 2024-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='house_number',
            field=models.PositiveIntegerField(verbose_name='Дом фирмы'),
        ),
    ]
