# Generated by Django 5.1.4 on 2024-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_contacts_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='factory_Product', to='shops.product', verbose_name='Продукты'),
        ),
    ]
